package com.melolchik.shopapp.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "COUNTRY".
 */
@Entity
public class Country {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private int countryId;

    @NotNull
    private String countryName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Country() {
    }

    public Country(Long id) {
        this.id = id;
    }

    @Generated
    public Country(Long id, int countryId, String countryName) {
        this.id = id;
        this.countryId = countryId;
        this.countryName = countryName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCountryId() {
        return countryId;
    }

    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    @NotNull
    public String getCountryName() {
        return countryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCountryName(@NotNull String countryName) {
        this.countryName = countryName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
