package com.melolchik.shopapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT".
*/
public class ProductDao extends AbstractDao<Product, Long> {

    public static final String TABLENAME = "PRODUCT";

    /**
     * Properties of entity Product.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ProductId = new Property(0, long.class, "productId", true, "PRODUCT_ID");
        public final static Property ProductName = new Property(1, String.class, "productName", false, "PRODUCT_NAME");
        public final static Property ProductImage = new Property(2, String.class, "productImage", false, "PRODUCT_IMAGE");
        public final static Property ProductPrice = new Property(3, Float.class, "productPrice", false, "PRODUCT_PRICE");
        public final static Property ProductCountry = new Property(4, Long.class, "productCountry", false, "PRODUCT_COUNTRY");
    }


    public ProductDao(DaoConfig config) {
        super(config);
    }
    
    public ProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT\" (" + //
                "\"PRODUCT_ID\" INTEGER PRIMARY KEY NOT NULL UNIQUE ," + // 0: productId
                "\"PRODUCT_NAME\" TEXT NOT NULL ," + // 1: productName
                "\"PRODUCT_IMAGE\" TEXT," + // 2: productImage
                "\"PRODUCT_PRICE\" REAL," + // 3: productPrice
                "\"PRODUCT_COUNTRY\" INTEGER);"); // 4: productCountry
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Product entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getProductId());
        stmt.bindString(2, entity.getProductName());
 
        String productImage = entity.getProductImage();
        if (productImage != null) {
            stmt.bindString(3, productImage);
        }
 
        Float productPrice = entity.getProductPrice();
        if (productPrice != null) {
            stmt.bindDouble(4, productPrice);
        }
 
        Long productCountry = entity.getProductCountry();
        if (productCountry != null) {
            stmt.bindLong(5, productCountry);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Product entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getProductId());
        stmt.bindString(2, entity.getProductName());
 
        String productImage = entity.getProductImage();
        if (productImage != null) {
            stmt.bindString(3, productImage);
        }
 
        Float productPrice = entity.getProductPrice();
        if (productPrice != null) {
            stmt.bindDouble(4, productPrice);
        }
 
        Long productCountry = entity.getProductCountry();
        if (productCountry != null) {
            stmt.bindLong(5, productCountry);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Product readEntity(Cursor cursor, int offset) {
        Product entity = new Product( //
            cursor.getLong(offset + 0), // productId
            cursor.getString(offset + 1), // productName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // productImage
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // productPrice
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // productCountry
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Product entity, int offset) {
        entity.setProductId(cursor.getLong(offset + 0));
        entity.setProductName(cursor.getString(offset + 1));
        entity.setProductImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProductPrice(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setProductCountry(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Product entity, long rowId) {
        entity.setProductId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Product entity) {
        if(entity != null) {
            return entity.getProductId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Product entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
