package com.melolchik.shopapp.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PURCHASE".
 */
@Entity
public class Purchase {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private int purchaseId;
    private int productId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Purchase() {
    }

    public Purchase(Long id) {
        this.id = id;
    }

    @Generated
    public Purchase(Long id, int purchaseId, int productId) {
        this.id = id;
        this.purchaseId = purchaseId;
        this.productId = productId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseId(int purchaseId) {
        this.purchaseId = purchaseId;
    }

    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
